### ISSUE TITLE
what do inputs represent?

### ISSUE THREAD

**Issue by amrnablus** [FlorisHoogenboom/keras-han-for-docla#1]
Hello and thanks for sharing your code!
I have a question, what do the input layers represent in this model? I think the first input represents the word indexes, so in that case what does input_2 represent? Is it the encoded states of the sentences? In that case shouldn't it be a float?

**Comment by FlorisHoogenboom** [comment]
The network itself only has a single input layer which you can find here:
https://github.com/FlorisHoogenboom/keras-han-for-docla/blob/5701798d9997e84b08b5ed0aed6c990bfcc51e13/keras_han/model.py#L110
The first dimension of this tensor is the batch_size you choose. The second dimension is the maximum number of sentences you allow per document and the third dimension is the maximum number of words per sentence you allow. This tensor contains your encoded document (E.g. using Keras' [Tokenizer](https://keras.io/preprocessing/text/)).

In the source you'll also find some other input layers, e.g. 
https://github.com/FlorisHoogenboom/keras-han-for-docla/blob/5701798d9997e84b08b5ed0aed6c990bfcc51e13/keras_han/model.py#L70
and
https://github.com/FlorisHoogenboom/keras-han-for-docla/blob/5701798d9997e84b08b5ed0aed6c990bfcc51e13/keras_han/model.py#L96

These aren't inputs of the whole network, but they are merely inputs of the parts of the network. Structuring things this way allows for a nicely, modular setup.

Hope this answers your question.

**Comment by amrnablus** [comment]
@FlorisHoogenboom Hey, sorry i missed your comments for some reason, thanks for the detailed explanation.
