### ISSUE TITLE
TypeError while running example in imdb_example.py

### ISSUE THREAD

**Issue by Ebipatei** [FlorisHoogenboom/keras-han-for-docla#5]
This is the error I got

TypeError                                 Traceback (most recent call last)
<ipython-input-8-52000e15d2a0> in <module>
    132 # Load the embeddings from a file
    133 embeddings = {}
--> 134 with open('C:/Users/UOU/Desktop/ebifolder/mpm/keras-han-for-docla/trialdata/glove.6B.100d.txt' % GLOVE_DIM, encoding='utf-8') as file:
    135     for line in file:
    136         values = line.split()

TypeError: not all arguments converted during string formatting

Any ideas?

**Comment by FlorisHoogenboom** [comment]
You've inserted the full path to the glove embedding you wish to use directly, therefore you should not try to format the sting using the `% GLOVE_DIM`variable.

**Comment by Ebipatei** [comment]
Thanks but am I also to remove it from this line as well?
embedding_matrix = np.random.random(
    (len(word_tokenizer.word_index) + 1, GLOVE_DIM)
)

coz when I did I got another error:
TypeError                                 Traceback (most recent call last)
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-12-69978c70c52e> in <module>
    154     embedding_vector = embeddings.get(word)
    155     if embedding_vector is not None:
--> 156         embedding_matrix[index] = embedding_vector
    157 
    158 

ValueError: setting an array element with a sequence.

**Comment by FlorisHoogenboom** [comment]
No, from your file path it seems you've chosen to use 100 dimensional glove embeddings. Hence glove dim should be 100. The best solution of course would be to just rely on the original string formatting in the path and keep that while changing it to your location. That way you have a single place where you set how large your embeddings are.

**Comment by Ebipatei** [comment]
Yes, I did that already, thanks.
