### ISSUE TITLE
predict on example model

### ISSUE THREAD

**Issue by Ebipatei** [FlorisHoogenboom/keras-han-for-docla#6]
Hi, how do I predict with the model?
Tried this but didn't work

print('Test...')
test_data = pd.read_csv('C:/Users/UOU/Desktop/ebifolder/mpm/keras-han-for-docla/trialdata/testData.tsv', sep='\t')
test_data = test_data['review'].values

result = han_model.predict(test_data)

**Comment by FlorisHoogenboom** [comment]
You will fist need to tokenize your data with the same tokenizer you've used during training and apply the embeddings (same as used during training ofcourse) to those tokens. Please follow the example and specifically for this part look at https://github.com/FlorisHoogenboom/keras-han-for-docla/blob/master/examples/imdb_example.py#L153.

**Comment by Ebipatei** [comment]
Alright thanks a lot.
